"""add confidence to documents

Revision ID: 5d1160ad6231
Revises: b175b3cb2578
Create Date: 2026-09-25 21:58:20.355300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d1160ad6231"
down_revision: Union[str, Sequence[str], None] = "b175b3cb2578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("confidence", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "confidence")
    # ### end Alembic commands ###
